export const PASSWORD_LIST_REQUEST = 'PASSWORD_LIST_REQUEST'
export const PASSWORD_LIST_SUCCESS = 'PASSWORD_LIST_SUCCESS'
export const PASSWORD_LIST_FAIL = 'PASSWORD_LIST_FAIL'


export const PASSWORD_DETAILS_REQUEST = 'PASSWORD_DETAILS_REQUEST'
export const PASSWORD_DETAILS_SUCCESS = 'PASSWORD_DETAILS_SUCCESS'
export const PASSWORD_DETAILS_FAIL = 'PASSWORD_DETAILS_FAIL'


export const PASSWORD_CREATE_REQUEST = 'PASSWORD_CREATE_REQUEST'
export const PASSWORD_CREATE_SUCCESS = 'PASSWORD_CREATE_SUCCESS'
export const PASSWORD_CREATE_FAIL = 'PASSWORD_CREATE_FAIL'