# Generated by Django 3.2.7 on 2021-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_apppass_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='passgroup',
            name='sub_group',
            field=models.ManyToManyField(blank=True, related_name='_base_passgroup_sub_group_+', to='base.PassGroup'),
        ),
    ]
