# Generated by Django 3.2.7 on 2021-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_passgroup_sub_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passgroup',
            name='sub_group',
            field=models.ManyToManyField(blank=True, related_name='sub_groups', to='base.PassGroup'),
        ),
    ]
