# Generated by Django 3.2.7 on 2021-11-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_passgroup_sub_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passgroup',
            name='sub_group',
        ),
        migrations.AddField(
            model_name='passgroup',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.passgroup'),
        ),
    ]
