# Generated by Django 3.2.7 on 2021-11-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211124_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passgroup',
            name='sub_group',
        ),
        migrations.AddField(
            model_name='passgroup',
            name='sub_group',
            field=models.ManyToManyField(blank=True, related_name='sub_groups', to='base.PassGroup'),
        ),
    ]
